# Generated by Django 4.0.6 on 2022-07-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='code',
            field=models.CharField(default='abc123', max_length=8),
        ),
    ]
