# Generated by Django 4.0.6 on 2022-07-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_quiz_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
        migrations.AddField(
            model_name='quiz',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
